# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2b69cb192317924e246b676e11cfa273e3a8ec54df8b50a4d1b8114d50ac357a41bd804ccd7f075d89f415e640526b06d0a5a48f98af7107a39223d9d572346

test:
  secret_key_base: ac4aab1392779c9f9f4a293016e85641596955a64e3d4e7c79b1f3be80be451a69394b2620f63a95b4d66c0386307dde4654b8ea9a22356c74150116aa9f450c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
